import { Job } from './types';

export const jobs: Job[] = [
  {
    id: 'job-1',
    startupId: 's1',
    startupName: 'ZettaCloud',
    startupLogoUrl: 'https://placehold.co/64x64/EEE/31343C/png?text=ZC',
    title: 'Frontend Component Lead',
    description: 'Migrate legacy dashboard to Tailwind CSS with a focus on atomic design patterns.',
    deliverables: ['20 reusable and well-documented React components', 'A comprehensive theming system for light and dark modes', 'Unit and integration tests with over 90% coverage'],
    duration: '10 Days',
    stipend: '₹8,000',
    skills: ['React', 'Tailwind', 'TypeScript'],
    status: 'Open',
    createdAt: '2024-05-10T09:00:00Z',
    type: 'task/project based',
    location: 'Bengaluru',
    remote: true,
    applicantsCount: 12,
    sector: 'DeepTech',
    compensationType: 'Paid',
  },
  {
    id: 'job-2',
    startupId: 's2',
    startupName: 'AgriFuture',
    startupLogoUrl: 'https://placehold.co/64x64/EEE/31343C/png?text=AF',
    title: 'Marketing Intern',
    description: 'Develop and execute a content strategy to grow our social media presence across various platforms. The ideal candidate is creative, data-driven, and passionate about sustainable agriculture.',
    deliverables: ['Detailed content calendar for 3 months', 'Weekly performance reports with key metrics (KPIs)', 'Achieve a 2x growth in follower count on Instagram and Twitter'],
    duration: '3 Months',
    stipend: '₹15,000/month',
    skills: ['Social Media Marketing', 'Content Creation', 'SEO'],
    status: 'Open',
    createdAt: '2024-05-08T11:00:00Z',
    type: 'internship',
    location: 'Pune',
    remote: false,
    applicantsCount: 45,
    sector: 'AgriTech',
    compensationType: 'Paid',
  },
  {
    id: 'job-3',
    startupId: 's3',
    startupName: 'HealthSphere',
    startupLogoUrl: 'https://placehold.co/64x64/EEE/31343C/png?text=HS',
    title: 'Co-founder for Tech',
    description: 'Join as a technical co-founder to lead product development for our innovative health-tech platform. We are seeking a visionary leader with a strong technical background and a desire to make a significant impact in healthcare.',
    deliverables: ['Successful launch of the Minimum Viable Product (MVP)', 'A clear and actionable technical roadmap for the next 2 years', 'Recruit and manage a high-performing engineering team'],
    duration: 'Ongoing',
    stipend: '10% Equity',
    skills: ['Full-Stack Development', 'Leadership', 'Product Management'],
    status: 'Open',
    createdAt: '2024-05-05T14:00:00Z',
    type: 'full-time',
    location: 'Remote',
    remote: true,
    applicantsCount: 5,
    sector: 'HealthTech',
    compensationType: 'Equity',
  },
  {
    id: 'job-4',
    startupId: 's4',
    startupName: 'FinConnect',
    startupLogoUrl: 'https://placehold.co/64x64/EEE/31343C/png?text=FC',
    title: 'UI/UX Design for Mobile App',
    description: 'Design a user-centric and intuitive interface for our new fintech mobile application. The goal is to create a seamless and engaging user experience that sets a new standard in the industry.',
    deliverables: ['High-fidelity mockups for all app screens', 'An interactive prototype for user testing and feedback', 'A comprehensive design system and style guide'],
    duration: '1 Month',
    skills: ['Figma', 'UI/UX Design', 'Mobile Design'],
    status: 'Open',
    createdAt: '2024-05-12T18:00:00Z',
    type: 'task/project based',
    location: 'Mumbai',
    remote: true,
    applicantsCount: 28,
    sector: 'FinTech',
    compensationType: 'Partnership',
  },
];
